### ISSUE TITLE
Add ZenHub option and map file

### ISSUE THREAD

**Issue by amanire** [isovera/enlabeler#5]
Invoke Enlabeler with ZenHub option:
`./enlabler --zenhub`

Next, prompt for a filename, with `labels-pipelines.json` as the default, which will be committed to the repository.

**Comment by hhedden-isovera** [comment]
For now, the Enlabeler script will use the `-z` option for ZenHub instead of `--zenhub`. Ideally, it should probably accept both.

**Comment by amanire** [comment]
I think this is going to have to stay out of scope for now.
